# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfcd7658bf732cb77875b05941972bdba1ecdf349a584cc0e4c34a6b6ed892c07815042bb9dfc3e183bae0dc406e564b9d99b0d8ad4bef10d57a2b7e5fa3814d

test:
  secret_key_base: b74c3be4e07b497efa7396b34fb3b780afc1d4b5b4ecc3dfeb0d5e955d2a27b497580c80d6496ba37838e17a63e115a83881d8f2086d961ae66b79881259976f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
