# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152f21cedeb8eeb60302fa0d1819540f6ad0de3e560f8d5aa046243d233257b5a05e51e8f6d8c3390a9a3b3aee0441dd6c61ac7bf9f846043cb82e6a321d78e5

test:
  secret_key_base: 5e6982e8885df5df2a9dc56b3ead2a80a152d223ad5288368ef757cc32861cb8d28eab4dda9841883f240c9bdf2977786f8c4b7263a2244161bb30529618ec46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
